- name: restart cron
  service:
    name: cron
    state: restarted
  become: yes

- name: restart supervisor
  service:
    name: supervisor
    state: restarted
  become: yes

- name: restart redis
  service:
    name: redis-server
    state: restarted
  become: yes
